import pandas as pd

# Comprehensive product type mapping dictionary
product_type_mapping = {
    # Beauty & Personal Care
    'Makeup': 'Beauty & Personal Care',
    'Skincare': 'Beauty & Personal Care',
    'Bodycare': 'Beauty & Personal Care',
    'Fragrance': 'Beauty & Personal Care',
    'Women Skincare': 'Beauty & Personal Care',
    'Women Bodycare': 'Beauty & Personal Care',
    'Women Makeup': 'Beauty & Personal Care',
    'Women Fragrance': 'Beauty & Personal Care',
    'Men Skincare': 'Beauty & Personal Care',
    'Men Bodycare': 'Beauty & Personal Care',
    'Men Fragrance': 'Beauty & Personal Care',
    'Men Deodorant': 'Beauty & Personal Care',
    'Parfum': 'Beauty & Personal Care',
    'Eau de Toilette': 'Beauty & Personal Care',
    'Eau de Parfum': 'Beauty & Personal Care',
    'Women Haircare': 'Beauty & Personal Care',
    
    # Bags & Luggage
    'Handbag': 'Bags & Luggage',
    'Travel Bag': 'Bags & Luggage',
    'Backpack': 'Bags & Luggage',
    'Backpacks': 'Bags & Luggage',
    'Clutch/Evening Bag': 'Bags & Luggage',
    'Evening Bag': 'Bags & Luggage',
    'Clutch Bag': 'Bags & Luggage',
    'Luggage': 'Bags & Luggage',
    'Luggages': 'Bags & Luggage',
    'Briefcase': 'Bags & Luggage',
    'Top Handle Bag': 'Bags & Luggage',
    'Crossbody Bag': 'Bags & Luggage',
    'Pouch': 'Bags & Luggage',
    'Shoulder Bag': 'Bags & Luggage',
    'Tote Bag': 'Bags & Luggage',
    'Satchel Bag': 'Bags & Luggage',
    'Mini Bag': 'Bags & Luggage',
    'Belt Bag': 'Bags & Luggage',
    'Messenger Bag': 'Bags & Luggage',
    'Hand-Carry Bag': 'Bags & Luggage',
    "Women's Shoulder Bag": 'Bags & Luggage',
    "Women's Tote": 'Bags & Luggage',
    "Women's Bag": 'Bags & Luggage',
    "Women's Shopper": 'Bags & Luggage',
    "Women's Crossbody": 'Bags & Luggage',
    "Women's Crossbody Bag": 'Bags & Luggage',
    "Women's Phone Bag": 'Bags & Luggage',
    "Women's Bowler Bag": 'Bags & Luggage',
    "Men's Backpack": 'Bags & Luggage',
    "Men's Duffle Bag": 'Bags & Luggage',
    "Men's Crossbody": 'Bags & Luggage',
    "Men's Messenger": 'Bags & Luggage',
    "Men's Belt Bag": 'Bags & Luggage',
    "Men's Tote": 'Bags & Luggage',
    "Men's Laptop Bag": 'Bags & Luggage',
    "Men's Sling Bag": 'Bags & Luggage',
    "Men's Duffle": 'Bags & Luggage',
    'Women Bag': 'Bags & Luggage',
    'Men Bag': 'Bags & Luggage',
    'Women Crossbody Bag': 'Bags & Luggage',
    'Women Tote Bag': 'Bags & Luggage',
    'Women Luggage': 'Bags & Luggage',
    "Men's Bags": 'Bags & Luggage',
    "Women's Bags": 'Bags & Luggage',
    'Men Bags': 'Bags & Luggage',
    
    # Women's Clothing
    "Women's Suit": 'Women\'s Clothing',
    "Women's Outfit": 'Women\'s Clothing',
    "Women's Outfits": 'Women\'s Clothing',
    "Women's Dress": 'Women\'s Clothing',
    "Women's Top": 'Women\'s Clothing',
    "Women's Pants": 'Women\'s Clothing',
    "Women's  Top": 'Women\'s Clothing',
    "Women's Shirt": 'Women\'s Clothing',
    'Cardigan Sweater': 'Women\'s Clothing',
    'Women Blazer': 'Women\'s Clothing',
    'Women Shirt': 'Women\'s Clothing',
    "Women's Coat": 'Women\'s Clothing',
    "Women's Jeans": 'Women\'s Clothing',
    "Women's T-Shirt": 'Women\'s Clothing',
    'Blouse': 'Women\'s Clothing',
    "Women's Sweater": 'Women\'s Clothing',
    "Women's Skirt": 'Women\'s Clothing',
    "Women's Shorts": 'Women\'s Clothing',
    "Women's Turtleneck": 'Women\'s Clothing',
    "Women's Tunic": 'Women\'s Clothing',
    "Women's Blouse": 'Women\'s Clothing',
    "Women's Hoodie": 'Women\'s Clothing',
    'women shirt': 'Women\'s Clothing',
    'Women Pant': 'Women\'s Clothing',
    'Women Shorts': 'Women\'s Clothing',
    'Women Skirt': 'Women\'s Clothing',
    'Women T-Shirt': 'Women\'s Clothing',
    'Women Hoodie': 'Women\'s Clothing',
    'Women Sweatshirt': 'Women\'s Clothing',
    'Women Jeans': 'Women\'s Clothing',
    'Women Dress': 'Women\'s Clothing',
    'Women Jumpsuit': 'Women\'s Clothing',
    "Women's Blouses": 'Women\'s Clothing',
    "Women's Blazers": 'Women\'s Clothing',
    "Women's Sweaters": 'Women\'s Clothing',
    "Women's T-Shirts": 'Women\'s Clothing',
    "Women's Suits": 'Women\'s Clothing',
    "Women's Skirts": 'Women\'s Clothing',
    "Women's Coats and Jackets": 'Women\'s Clothing',
    "Women's Hoodies": 'Women\'s Clothing',
    "Women's Joggers": 'Women\'s Clothing',
    "Women's Sweatshirts": 'Women\'s Clothing',
    "Women's Tops": 'Women\'s Clothing',
    "Women's Shirts": 'Women\'s Clothing',
    "Women's Dresses": 'Women\'s Clothing',
    "Women's Tees": 'Women\'s Clothing',
    "Women's Coats & Jackets": 'Women\'s Clothing',
    'Women Legging': 'Women\'s Clothing',
    'Women Leggings': 'Women\'s Clothing',
    'Women Pants': 'Women\'s Clothing',
    'Women Skirts': 'Women\'s Clothing',
    'Women Suits & Separates': 'Women\'s Clothing',
    'Women Sweaters': 'Women\'s Clothing',
    'Women Sweatshirts': 'Women\'s Clothing',
    'Women Tops': 'Women\'s Clothing',
    'Women Plus Size': 'Women\'s Clothing',
    'Women Jacket': 'Women\'s Clothing',
    'Dress': 'Women\'s Clothing',
    'Short Dress': 'Women\'s Clothing',
    'Shirt Dress': 'Women\'s Clothing',
    'Midi Dress': 'Women\'s Clothing',
    'Jumpsuit': 'Women\'s Clothing',
    'Party Dress': 'Women\'s Clothing',
    'Mini Dress': 'Women\'s Clothing',
    'Women Bodysuit': 'Women\'s Clothing',
    'Women Tank Top': 'Women\'s Clothing',
    'Women Romper': 'Women\'s Clothing',
    'Women Party & Cocktail Dresses': 'Women\'s Clothing',
    'Dresses & Jumpsuits': 'Women\'s Clothing',
    'Outerwear': 'Women\'s Clothing',
    'Sweaters': 'Women\'s Clothing',
    'Bottoms': 'Women\'s Clothing',
    'Tops': 'Women\'s Clothing',
    'Women Denim': 'Women\'s Clothing',
    'Women Basics & T-shirts': 'Women\'s Clothing',
    "Women's Denim": 'Women\'s Clothing',
    'Women Jogger': 'Women\'s Clothing',
    
    # Men's Clothing
    "Men's Suits": 'Men\'s Clothing',
    "Men's Suit": 'Men\'s Clothing',
    "Men's Outfit": 'Men\'s Clothing',
    "Men's Collection": 'Men\'s Clothing',
    "Men's Dress": 'Men\'s Clothing',
    "Men's T‑Shirt": 'Men\'s Clothing',
    "Men's Pants": 'Men\'s Clothing',
    "Men's Jeans": 'Men\'s Clothing',
    "Men's Shirt": 'Men\'s Clothing',
    "Men's Overshirt": 'Men\'s Clothing',
    "Men's Hoodie": 'Men\'s Clothing',
    "Men's Jacket": 'Men\'s Clothing',
    "Men's Shorts": 'Men\'s Clothing',
    "Men's Polo": 'Men\'s Clothing',
    "Men's Joggers": 'Men\'s Clothing',
    "Men's Blazer": 'Men\'s Clothing',
    "Men's Coat": 'Men\'s Clothing',
    "Men's Suit Pants": 'Men\'s Clothing',
    "Men's Sweater": 'Men\'s Clothing',
    "Men's Vest": 'Men\'s Clothing',
    "Men's Dress Shirt": 'Men\'s Clothing',
    "Men's Suit Jacket": 'Men\'s Clothing',
    "Men's Dress Pants": 'Men\'s Clothing',
    "Men's Shirt Jacket": 'Men\'s Clothing',
    "Men's Sweatshirt": 'Men\'s Clothing',
    "Men's Cardigan": 'Men\'s Clothing',
    "Men's Flannel Shirt": 'Men\'s Clothing',
    "Men's Base Layer": 'Men\'s Clothing',
    'Men Shirt': 'Men\'s Clothing',
    'Men T-Shirt': 'Men\'s Clothing',
    'Men Button-Down Shirt': 'Men\'s Clothing',
    'Men Trouser': 'Men\'s Clothing',
    'Men Jogger': 'Men\'s Clothing',
    'Men Polo Shirt': 'Men\'s Clothing',
    'Men Sweatshirt': 'Men\'s Clothing',
    'Men  Jogger': 'Men\'s Clothing',
    'Men Hoodie': 'Men\'s Clothing',
    'Men Tank Top': 'Men\'s Clothing',
    'Men blazer': 'Men\'s Clothing',
    'Men Jacket': 'Men\'s Clothing',
    'Men Blazer': 'Men\'s Clothing',
    'Men Jeans': 'Men\'s Clothing',
    'Men Dress Shirt': 'Men\'s Clothing',
    'Men Jumpsuit': 'Men\'s Clothing',
    "Men's Casual Pants": 'Men\'s Clothing',
    "Men's Shirts": 'Men\'s Clothing',
    "Men's Sweaters": 'Men\'s Clothing',
    "Men's T-Shirts": 'Men\'s Clothing',
    "Men's Polos": 'Men\'s Clothing',
    "Men's Shorts": 'Men\'s Clothing',
    "Men's Coats and Jackets": 'Men\'s Clothing',
    "Men's Hoodies": 'Men\'s Clothing',
    "Men's Joggers": 'Men\'s Clothing',
    "Men's Sweatshirts": 'Men\'s Clothing',
    "Men's Dress Pants": 'Men\'s Clothing',
    "Men's Dress Shirts": 'Men\'s Clothing',
    "Men's Sports Coats": 'Men\'s Clothing',
    "Men's Casual Shirts": 'Men\'s Clothing',
    "Men's Pants": 'Men\'s Clothing',
    "Men's Long-Sleeve Shirts": 'Men\'s Clothing',
    "Men's Short-Sleeve Shirts": 'Men\'s Clothing',
    "Men's Coats & Jackets": 'Men\'s Clothing',
    'Men Sweatpants': 'Men\'s Clothing',
    'Men Dress Pants': 'Men\'s Clothing',
    'Men Denim': 'Men\'s Clothing',
    'Men Basics & T-shirts': 'Men\'s Clothing',
    "Men's Denim": 'Men\'s Clothing',
    'Knitted Garment': 'Men\'s Clothing',
    "Men's Blazers": 'Men\'s Clothing',
    
    # Denim (General)
    'Denim Jeans': 'Denim',
    'Denim Jackets': 'Denim',
    'Denim Jacket': 'Denim',
    'Denim  Jacket': 'Denim',
    'Denim ackets': 'Denim',
    'Denim': 'Denim',
    'Jackets': 'Denim',
    
    # Children's Clothing
    "Kids' Denim Jacket": 'Kids Clothing',
    "Kids' Jacket": 'Kids Clothing',
    "Kids' Vest": 'Kids Clothing',
    "Kids' Dress": 'Kids Clothing',
    "Kids' Hoodie": 'Kids Clothing',
    "Kids' Activewear": 'Kids Clothing',
    "Kids' Outfit Set": 'Kids Clothing',
    "Kids' Cardigan": 'Kids Clothing',
    'Boys T-Shirt': 'Kids Clothing',
    'Boys Jeans': 'Kids Clothing',
    'Boys Sweatshirt': 'Kids Clothing',
    'Boys Pants': 'Kids Clothing',
    'Boys Shirt': 'Kids Clothing',
    'Girls Dress': 'Kids Clothing',
    'Girls Leggings': 'Kids Clothing',
    'Girls Sweatshirt': 'Kids Clothing',
    'Girls Shorts': 'Kids Clothing',
    'Girls Blouse': 'Kids Clothing',
    'Baby Romper': 'Kids Clothing',
    'Baby Sweater': 'Kids Clothing',
    'Boys Outerwear': 'Kids Clothing',
    'Girls Outerwear': 'Kids Clothing',
    'Boys Jacket': 'Kids Clothing',
    'Girls Skirt': 'Kids Clothing',
    'Boys Joggers': 'Kids Clothing',
    'Girls Hoodie': 'Kids Clothing',
    'Boys Polo': 'Kids Clothing',
    'Boys Shorts': 'Kids Clothing',
    'Boys Long Sleeve': 'Kids Clothing',
    "Boys' Clothing": 'Kids Clothing',
    "Girls' Clothing": 'Kids Clothing',
    "Babies' Clothing": 'Kids Clothing',
    "Boys' Accessories": 'Kids Clothing',
    "Girls' Accessories": 'Kids Clothing',
    'Kids Swimwear': 'Kids Clothing',
    
    # Shoes & Footwear
    'Women Footwear': 'Footwear',
    "Women's Shoes": 'Footwear',
    "Women's Sandal": 'Footwear',
    "Women's Slingback": 'Footwear',
    "Women's Flat": 'Footwear',
    "Women's Loafer": 'Footwear',
    "Women's Pump": 'Footwear',
    "Women's Boot": 'Footwear',
    "Women's Sandals": 'Footwear',
    "Women's Espadrilles": 'Footwear',
    "Women's Pumps": 'Footwear',
    "Women's Boots": 'Footwear',
    "Women's Slingbacks": 'Footwear',
    "Women's Flats": 'Footwear',
    "Women's Flip‑Flops": 'Footwear',
    "Men's Boots": 'Footwear',
    "Men's Shoes": 'Footwear',
    "Men's Trainers": 'Footwear',
    "Men's Loafers": 'Footwear',
    "Men's Sandals": 'Footwear',
    "Men's Espadrilles": 'Footwear',
    "Men's Flip-Flops": 'Footwear',
    "Men's Moccasins": 'Footwear',
    "Men's Slip-Ons": 'Footwear',
    'Women Shoes': 'Footwear',
    'Men Shoes': 'Footwear',
    'Women Boots': 'Footwear',
    'Men Boots': 'Footwear',
    'Women Sneakers': 'Footwear',
    'Women Clogs': 'Footwear',
    'Comfort': 'Footwear',
    'Dress Shoes': 'Footwear',
    'Loafers & Slip-Ons': 'Footwear',
    'Sneakers & Athletic': 'Footwear',
    'Oxfords & Derbys': 'Footwear',
    'Sandals & Flip-Flops': 'Footwear',
    'Slippers': 'Footwear',
    'Swimwear': 'Footwear',
    
    # Sneakers (subcategory of Footwear)
    'Basketball Sneakers': 'Sneakers',
    'Skateboarding Sneakers': 'Sneakers',
    'Running-Inspired Sneakers': 'Sneakers',
    'Running Sneakers': 'Sneakers',
    'Running / Retro Sneakers': 'Sneakers',
    'Accessible / Slip-on Sneakers': 'Sneakers',
    'Trail Sneakers': 'Sneakers',
    'Luxury Collaboration Sneakers': 'Sneakers',
    'Lifestyle Sneakers': 'Sneakers',
    'Sustainable Sneakers': 'Sneakers',
    'Performance Sneakers': 'Sneakers',
    'Other Sneakers': 'Sneakers',
    'Trail Running Sneakers': 'Sneakers',
    'Retro Running Sneakers': 'Sneakers',
    'Elite Racing Sneakers': 'Sneakers',
    'Indoor Soccer Sneakers': 'Sneakers',
    'Retro Training Sneakers': 'Sneakers',
    'Special Edition Sneakers': 'Sneakers',
    'Classic Sneakers': 'Sneakers',
    'Designer Sneakers': 'Sneakers',
    'Futuristic Lifestyle Sneakers': 'Sneakers',
    'Reflective Running Sneakers': 'Sneakers',
    'Minimalist Lifestyle Sneakers': 'Sneakers',
    'Chunky Lifestyle Sneakers': 'Sneakers',
    'Soccer Inspired Sneakers': 'Sneakers',
    
    # Jewelry & Accessories
    'Watch': 'Jewelry & Accessories',
    'Jewelry': 'Jewelry & Accessories',
    'Sunglasses': 'Jewelry & Accessories',
    'Belt': 'Jewelry & Accessories',
    'Cap': 'Jewelry & Accessories',
    'Hat': 'Jewelry & Accessories',
    'Gloves': 'Jewelry & Accessories',
    'Wallet': 'Jewelry & Accessories',
    'Scarf': 'Jewelry & Accessories',
    'Small Goods': 'Jewelry & Accessories',
    'Eyewear': 'Jewelry & Accessories',
    'Glasses': 'Jewelry & Accessories',
    'Hats': 'Jewelry & Accessories',
    'Caps': 'Jewelry & Accessories',
    'Earings': 'Jewelry & Accessories',
    'Necklace': 'Jewelry & Accessories',
    'Bracelet': 'Jewelry & Accessories',
    'Ring': 'Jewelry & Accessories',
    'Bendant': 'Jewelry & Accessories',
    'Bangle': 'Jewelry & Accessories',
    'Cuff': 'Jewelry & Accessories',
    'Industrial': 'Jewelry & Accessories',
    'Chain Link': 'Jewelry & Accessories',
    'Charm': 'Jewelry & Accessories',
    'Minimalist': 'Jewelry & Accessories',
    'Stud': 'Jewelry & Accessories',
    'Hoop': 'Jewelry & Accessories',
    'Drop': 'Jewelry & Accessories',
    'Statement': 'Jewelry & Accessories',
    'Pendant': 'Jewelry & Accessories',
    'Choker': 'Jewelry & Accessories',
    'Chain': 'Jewelry & Accessories',
    'Band': 'Jewelry & Accessories',
    'Modern': 'Jewelry & Accessories',
    'Classic': 'Jewelry & Accessories',
    "Women's Necklace": 'Jewelry & Accessories',
    "Men's Rings": 'Jewelry & Accessories',
    "Men's Bracelet": 'Jewelry & Accessories',
    "Men's Necklace": 'Jewelry & Accessories',
    "Men's Earrings": 'Jewelry & Accessories',
    "Men's Ring": 'Jewelry & Accessories',
    "Men's Watch Accessory": 'Jewelry & Accessories',
    "Men's Anklet": 'Jewelry & Accessories',
    "Men's Sunglasses": 'Jewelry & Accessories',
    'Men Belt': 'Jewelry & Accessories',
    'Men Wallet': 'Jewelry & Accessories',
    'Men Hat': 'Jewelry & Accessories',
    'Men Scarf': 'Jewelry & Accessories',
    'Men Necklace': 'Jewelry & Accessories',
    'Men Gloves': 'Jewelry & Accessories',
    'Men Hair Accessory': 'Jewelry & Accessories',
    'Women Belt': 'Jewelry & Accessories',
    'Women Gloves': 'Jewelry & Accessories',
    'Women Scarf': 'Jewelry & Accessories',
    'Women Wallet': 'Jewelry & Accessories',
    'Women Hair Accessory': 'Jewelry & Accessories',
    'Women Hat': 'Jewelry & Accessories',
    'Women Earrings': 'Jewelry & Accessories',
    'Women Necklace': 'Jewelry & Accessories',
    'Women Bracelet': 'Jewelry & Accessories',
    'Women Ring': 'Jewelry & Accessories',
    'Women Watch': 'Jewelry & Accessories',
    "Men's Belts": 'Jewelry & Accessories',
    "Men's Hats": 'Jewelry & Accessories',
    "Men's Scarves": 'Jewelry & Accessories',
    "Men's Sunglasses": 'Jewelry & Accessories',
    "Men's Wallets": 'Jewelry & Accessories',
    "Women's Belts": 'Jewelry & Accessories',
    "Women's Hats": 'Jewelry & Accessories',
    "Women's Scarves": 'Jewelry & Accessories',
    "Women's Wallets": 'Jewelry & Accessories',
    "Men's Necklaces": 'Jewelry & Accessories',
    "Men's Ties": 'Jewelry & Accessories',
    "Women's Sunglasses": 'Jewelry & Accessories',
    "Men's Socks": 'Jewelry & Accessories',
    "Women's Socks": 'Jewelry & Accessories',
    "Men's Bracelets": 'Jewelry & Accessories',
    "Men's Earrings": 'Jewelry & Accessories',
    "Women's Bracelets": 'Jewelry & Accessories',
    "Women's Necklaces": 'Jewelry & Accessories',
    "Women's Earrings": 'Jewelry & Accessories',
    'Aviator': 'Jewelry & Accessories',
    'Cat Eye': 'Jewelry & Accessories',
    'Round': 'Jewelry & Accessories',
    'Square': 'Jewelry & Accessories',
    'Rectangular': 'Jewelry & Accessories',
    'Pilot': 'Jewelry & Accessories',
    'Navigator': 'Jewelry & Accessories',
    'Oval': 'Jewelry & Accessories',
    'Bifold Wallet': 'Jewelry & Accessories',
    'Long Wallet': 'Jewelry & Accessories',
    'Compact Wallet': 'Jewelry & Accessories',
    'Reversible Belt': 'Jewelry & Accessories',
    'Classic Belt': 'Jewelry & Accessories',
    'Dress Belt': 'Jewelry & Accessories',
    'Casual Belt': 'Jewelry & Accessories',
    'Bracelets': 'Jewelry & Accessories',
    'Ties & Pocket Squares': 'Jewelry & Accessories',
    'Watches': 'Jewelry & Accessories',
    'Sunglasses & Eyewear': 'Jewelry & Accessories',
    'Men Sack': 'Jewelry & Accessories',
    'Women Sack': 'Jewelry & Accessories',
    "Men's Accessory": 'Jewelry & Accessories',
    
    # Underwear & Intimates
    'Men Underwear': 'Underwear & Intimates',
    'Women Underwear': 'Underwear & Intimates',
    'Women Lingerie': 'Underwear & Intimates',
    'Women Bra': 'Underwear & Intimates',
    'Women Sports Bra': 'Underwear & Intimates',
    'Women Hosiery & Shapewear': 'Underwear & Intimates',
    "Men's Underwear": 'Underwear & Intimates',
    "Women's Pajamas": 'Underwear & Intimates',
    "Women's Loungewear": 'Underwear & Intimates',
    'Men Loungewear': 'Underwear & Intimates',
    'Men Sleepwear': 'Underwear & Intimates',
    'Women Sleepwear': 'Underwear & Intimates',
    'Men Lounge': 'Underwear & Intimates',
    
    # Swimwear
    'Men Swimwear': 'Swimwear',
    'Women Swimwear': 'Swimwear',
    'Men Swim Trunks': 'Swimwear',
    'Women Cover Ups': 'Swimwear',
    "Men's Swimwear": 'Swimwear',
    "Women's Swimwear": 'Swimwear',
    
    # Sportswear & Activewear
    'Men Sportswear': 'Sportswear & Activewear',
    'Women Sportswear': 'Sportswear & Activewear',
    'Women Activewear': 'Sportswear & Activewear',
    'Women Yoga Mat': 'Sportswear & Activewear',
    'Men Activewear': 'Sportswear & Activewear',
    
    # Home & Living
    'Pillow Cover': 'Home & Living',
    'Floor Cushion': 'Home & Living',
    'Pillow Insert': 'Home & Living',
    'Duvet Cover Set': 'Home & Living',
    'Picnic Blanket': 'Home & Living',
    'Decorative Rug': 'Home & Living',
    'Bathroom Accessory': 'Home & Living',
    'Baby Blanket': 'Home & Living',
    'Sheet Set': 'Home & Living',
    'Blanket': 'Home & Living',
    'Throw Blanket': 'Home & Living',
    'Towel Set': 'Home & Living',
    'Kitchen Towel': 'Home & Living',
    'Curtain': 'Home & Living',
    'Wall Décor': 'Home & Living',
    'Home Fragrance': 'Home & Living',
    'Bath Mat': 'Home & Living',
    'Storage Basket': 'Home & Living',
    'Dining Textile': 'Home & Living',
    'Storage Boxes': 'Home & Living',
    'Home Decor': 'Home & Living',
    'Home Lighting': 'Home & Living',
    'Home Textiles': 'Home & Living',
    
    # Electronics - Smartphones
    'iPhone 16': 'Smartphones',
    'Plus': 'Smartphones',
    'Pro': 'Smartphones',
    'Pro Max': 'Smartphones',
    'iPhone 15': 'Smartphones',
    'iPhone 14': 'Smartphones',
    'iPhone 13': 'Smartphones',
    'iPhone 12': 'Smartphones',
    'Mini': 'Smartphones',
    'iPhone 11': 'Smartphones',
    'iPhone 8': 'Smartphones',
    'iPhone X': 'Smartphones',
    'iPhone 7': 'Smartphones',
    'SE': 'Smartphones',
    'iPhone 6': 'Smartphones',
    'iPhone 5': 'Smartphones',
    '4S': 'Smartphones',
    'iPhone 4': 'Smartphones',
    'Galaxy S': 'Smartphones',
    'S Plus': 'Smartphones',
    'Ultra': 'Smartphones',
    'FE': 'Smartphones',
    'Z Flip 7': 'Smartphones',
    'Z Fold 7': 'Smartphones',
    'S23Plus': 'Smartphones',
    'A55': 'Smartphones',
    'A35': 'Smartphones',
    'A14 SG': 'Smartphones',
    'A15': 'Smartphones',
    '1TB ROM': 'Smartphones',
    '512GB ROM': 'Smartphones',
    '256GB ROM': 'Smartphones',
    'Note 21': 'Smartphones',
    'Fold 4': 'Smartphones',
    'Flip 4': 'Smartphones',
    'F42': 'Smartphones',
    'F63': 'Smartphones',
    'F02s': 'Smartphones',
    'F13': 'Smartphones',
    'M02': 'Smartphones',
    'M12': 'Smartphones',
    'M22': 'Smartphones',
    'M32': 'Smartphones',
    'M52': 'Smartphones',
    'S21': 'Smartphones',
    'Note 20 Ultra': 'Smartphones',
    'Z Flip': 'Smartphones',
    'Z Fold 3': 'Smartphones',
    'A02': 'Smartphones',
    'A12': 'Smartphones',
    'A22': 'Smartphones',
    'A32': 'Smartphones',
    'A42': 'Smartphones',
    'A52': 'Smartphones',
    'A73': 'Smartphones',
    'Core': 'Smartphones',
    'Quantum': 'Smartphones',
    'M01 S': 'Smartphones',
    'M31 S': 'Smartphones',
    'S10 S': 'Smartphones',
    'S11': 'Smartphones',
    'Plus 5G': 'Smartphones',
    'Note 11': 'Smartphones',
    'Note 10 Plus': 'Smartphones',
    'Note 10 G': 'Smartphones',
    'Fold': 'Smartphones',
    'A11': 'Smartphones',
    'A21': 'Smartphones',
    'A31': 'Smartphones',
    'A41': 'Smartphones',
    'A51': 'Smartphones',
    'A71': 'Smartphones',
    'A81': 'Smartphones',
    'M11': 'Smartphones',
    'M21': 'Smartphones',
    'M31': 'Smartphones',
    'M41': 'Smartphones',
    'J3': 'Smartphones',
    'J5': 'Smartphones',
    'J4 Plus': 'Smartphones',
    'J6 Plus': 'Smartphones',
    'Galaxy': 'Smartphones',
    'Note 10': 'Smartphones',
    'S10': 'Smartphones',
    'S9 Plus': 'Smartphones',
    'J7': 'Smartphones',
    'J9': 'Smartphones',
    'A7': 'Smartphones',
    'A6 Plus': 'Smartphones',
    'A9': 'Smartphones',
    'A8 Plus': 'Smartphones',
    'A8': 'Smartphones',
    'A10': 'Smartphones',
    '8a': 'Smartphones',
    '9': 'Smartphones',
    '9 Pro': 'Smartphones',
    '9 Pro XL': 'Smartphones',
    'Pro Fold': 'Smartphones',
    '7a': 'Smartphones',
    '8 Pro': 'Smartphones',
    '7 Pro': 'Smartphones',
    '6a': 'Smartphones',
    '5a 5G': 'Smartphones',
    '6 Pro': 'Smartphones',
    '4a': 'Smartphones',
    '4a SG': 'Smartphones',
    '3a': 'Smartphones',
    '3a Xl': 'Smartphones',
    '4 XL': 'Smartphones',
    '3': 'Smartphones',
    
    # Electronics - TVs
    '85-inches': 'Televisions',
    '75-inches': 'Televisions',
    '55-inches': 'Televisions',
    '65-inches': 'Televisions',
    '77-inches': 'Televisions',
    '83-inches': 'Televisions',
    '43-inches': 'Televisions',
    '50-inches': 'Televisions',
    '48-inches': 'Televisions',
    '42-inches': 'Televisions',
    '49-inches': 'Televisions',
    '82-inches': 'Televisions',
    '58-inches': 'Televisions',
    '40-inches': 'Televisions',
    'G5': 'Televisions',
    'C5': 'Televisions',
    'B5': 'Televisions',
    'M5': 'Televisions',
    '99 Series': 'Televisions',
    '90 Series': 'Televisions',
    '85 Series': 'Televisions',
    '80 Series': 'Televisions',
    '75 Series': 'Televisions',
    '70 Series': 'Televisions',
    'G4': 'Televisions',
    'C4': 'Televisions',
    'B4': 'Televisions',
    'M4': 'Televisions',
    'G3': 'Televisions',
    'C3': 'Televisions',
    'B3': 'Televisions',
    'M3': 'Televisions',
    'G2': 'Televisions',
    'C2': 'Televisions',
    'B2': 'Televisions',
    'M2': 'Televisions',
    'G1': 'Televisions',
    'C1': 'Televisions',
    'B1': 'Televisions',
    'M1': 'Televisions',
    'GX': 'Televisions',
    'CX': 'Televisions',
    'BX': 'Televisions',
    'MX': 'Televisions',
    
    # Electronics - Computers & Tablets
    'Laptop 6': 'Computers & Tablets',
    'Tablet (2-in-1)': 'Computers & Tablets',
    'Laptop (2-in-1)': 'Computers & Tablets',
    'Desktop (All-in-One)': 'Computers & Tablets',
    'Laptop': 'Computers & Tablets',
    'Interactive Whiteboard (Hub)': 'Computers & Tablets',
    'Accessory': 'Computers & Tablets',
    'Tablet': 'Computers & Tablets',
    'Tablet (RT)': 'Computers & Tablets',
    'Mobile Workstation': 'Computers & Tablets',
    'Laptop (G-Series)': 'Computers & Tablets',
    'Gaming Laptop (G-Series)': 'Computers & Tablets',
    'Gaming Laptop (Alienware)': 'Computers & Tablets',
    'Gaming Laptop': 'Computers & Tablets',
    'Convertible Laptop': 'Computers & Tablets',
    'Business Laptop': 'Computers & Tablets',
    'Dual-Screen Laptop': 'Computers & Tablets',
    'Tablet Hybrid': 'Computers & Tablets',
    'Creator Laptop': 'Computers & Tablets',
    'Eco Laptop': 'Computers & Tablets',
    'Netbook': 'Computers & Tablets',
    'Dual-Screen Device': 'Computers & Tablets',
    'Interactive Whiteboard': 'Computers & Tablets',
    'Desktop': 'Computers & Tablets',
    'Detachable Tablet': 'Computers & Tablets',
    '2-in-1 Laptop': 'Computers & Tablets',
    'All-in-One': 'Computers & Tablets',
    'Detachable Laptop': 'Computers & Tablets',
    'Detachable Chromebook': 'Computers & Tablets',
    'Laptop (Chromebook)': 'Computers & Tablets',
    'Convertible Chromebook': 'Computers & Tablets',
    'Detachable': 'Computers & Tablets',
    'Gaming Tablet': 'Computers & Tablets',
    '13-inches with M3 Chip': 'Computers & Tablets',
    '15-inches with M3 Chip': 'Computers & Tablets',
    '14-incehs with M4 Chip': 'Computers & Tablets',
    '14-inches with M4 Pro Chip': 'Computers & Tablets',
    '16-inches with M4 Chip': 'Computers & Tablets',
    '16-inches': 'Computers & Tablets',
    '14-inches': 'Computers & Tablets',
    '13.6-inches': 'Computers & Tablets',
    '13.3-inches': 'Computers & Tablets',
    '13.2-inches': 'Computers & Tablets',
    '14.2-inches': 'Computers & Tablets',
    '16.2-inches': 'Computers & Tablets',
    '15.4-inches': 'Computers & Tablets',
    '13-inches': 'Computers & Tablets',
    '13-inches + Touch Bar': 'Computers & Tablets',
    '13.3-innches': 'Computers & Tablets',
    '12-inches': 'Computers & Tablets',
    '13-inches + Touch Screen': 'Computers & Tablets',
    '15-inches': 'Computers & Tablets',
    '15-inches + Touch Screen': 'Computers & Tablets',
    '17-inches': 'Computers & Tablets',
    '11-inches with M2 Chip': 'Computers & Tablets',
    '13-inches  with M2 Chip': 'Computers & Tablets',
    '11-inches with M4 Chip': 'Computers & Tablets',
    '13-inches with M4 Chip': 'Computers & Tablets',
    '8.3-inches with A17 Chip': 'Computers & Tablets',
    '10.9inches': 'Computers & Tablets',
    '12.9-inches': 'Computers & Tablets',
    '10.9-inches': 'Computers & Tablets',
    '11-inches': 'Computers & Tablets',
    '8.3-inches': 'Computers & Tablets',
    '10.2-inches': 'Computers & Tablets',
    '7.9-inches': 'Computers & Tablets',
    '10.5-inches': 'Computers & Tablets',
    '12.- inches': 'Computers & Tablets',
    
    # Electronics - Wearables
    'Enhanced Health-tracking': 'Wearables',
    'Premium Titanium': 'Wearables',
    'Black Titanium Color Option': 'Wearables',
    'Offers Onboard Siri Processing': 'Wearables',
    'Offers core functionalities': 'Wearables',
    'GPS + Celluar Support': 'Wearables',
    'GPS': 'Wearables',
    'Smart': 'Wearables',
    'No GPS': 'Wearables',
    'H2 Chip': 'Audio & Electronics',
    'Active Noise Cancellation': 'Audio & Electronics',
    'Personalized Spatial Audio': 'Audio & Electronics',
    'H1 Chip': 'Audio & Electronics',
    'Earbuds': 'Audio & Electronics',
    
    # Electronics - Gaming & VR
    'PlayStation 5, PC': 'Gaming & VR',
    'PlayStation': 'Gaming & VR',
    'Starfield': 'Gaming & VR',
    'PLA': 'Gaming & VR',
    'Xbox Series X/S': 'Gaming & VR',
    'Xbox One': 'Gaming & VR',
    'Windows': 'Gaming & VR',
    'Xbox': 'Gaming & VR',
    'PC (Steam)': 'Gaming & VR',
    'Meta Quest': 'Gaming & VR',
    'Meta Quest 2': 'Gaming & VR',
    'Meta Quest, Rift': 'Gaming & VR',
    'Oculus Quest, Rift': 'Gaming & VR',
    'Oculus Rift': 'Gaming & VR',
    'Oculus Rift Dev Kits': 'Gaming & VR',
    'VIVE Focus, VIVE Pro': 'Gaming & VR',
    'VIVE, VIVE Pro': 'Gaming & VR',
    'VIVE': 'Gaming & VR',
    'VR Headsets': 'Gaming & VR',
    
    # Watches (detailed categories)
    "Diver's Watch": 'Watches',
    'Chronograph Watch': 'Watches',
    'GMT Watch': 'Watches',
    'Explorer/Field Watch': 'Watches',
    'Luxury Sports Watch': 'Watches',
    'Luxury Dress Watch': 'Watches',
    'Pilot-Inspired Watch': 'Watches',
    "Professional Diver's Watch": 'Watches',
    'Classic Dress Watch': 'Watches',
    'Regatta Chronograph Watch': 'Watches',
    'Classic Dual Time Watch': 'Watches',
    'Grand Complication Watch': 'Watches',
    'Annual Calendar Watch': 'Watches',
    'Pilot Travel Time Watch': 'Watches',
    'Chronograph Sports Watch': 'Watches',
    'Luxury Watch': 'Watches',
    "Ladies' Watch": 'Watches',
    'Perpetual Calendar Watch': 'Watches',
    'Tourbillon Chronograph Watch': 'Watches',
    'Split-Seconds Chronograph GMT Watch': 'Watches',
    'Skeleton/Ultra-Thin Watch': 'Watches',
    'Skeleton Tourbillon Watch': 'Watches',
    'Ultra-Thin Watch': 'Watches',
    'Ultra-Thin Perpetual Calendar Watch': 'Watches',
    'Tourbillon Watch': 'Watches',
    "Diver's Chronograph Watch": 'Watches',
    'Flying Tourbillon GMT Watch': 'Watches',
    'Special Edition Chronograph Watch': 'Watches',
    'Limited Edition Chronograph Watch': 'Watches',
    'Dress Watch': 'Watches',
    'Sport Watch': 'Watches',
    'Special/Limited Edition Watch': 'Watches',
    'Heritage/Dress Watch': 'Watches',
    'High-Complication Dress Watch': 'Watches',
    'Jump Hour Watch': 'Watches',
    'Jewelry Watch Watch': 'Watches',
    'Fitness Tracking Watch': 'Watches',
    'Fitness Watch': 'Watches',
    'Lifestyle Watch': 'Watches',
    'Multisport Watch': 'Watches',
    'Rugged Outdoor Watch': 'Watches',
    'Premium Multisport Watch': 'Watches',
    'Ultra-Performance Watch': 'Watches',
    'Smartwatch': 'Watches',
    'Fitness Tracker': 'Watches',
    'Kids Tracker': 'Watches',
    'Fitness Smartwatch': 'Watches',
    'Health and Fitness Smartwatch': 'Watches',
    'Premium Smartwatch': 'Watches',
    'Advanced Fitness Smartwatch': 'Watches',
    'Premium Multisport GPS': 'Watches',
    'Outdoor Multisport GP': 'Watches',
    'Premium Outdoor Multisport GPS': 'Watches',
    'Flagship Outdoor Multisport GPS': 'Watches',

    
    # Audio & Speakers
    'Ultra-Portable Speaker': 'Audio & Electronics',
    'Mid-Sized Portable Speaker': 'Audio & Electronics',
    'Large Portable Speaker': 'Audio & Electronics',
    'Party Speaker': 'Audio & Electronics',
    'Portable Bluetooth Speaker': 'Audio & Electronics',
    '360° Sound Portable Speaker': 'Audio & Electronics',
    'High-Power Portable Speaker': 'Audio & Electronics',
    'Smart & Home Speaker': 'Audio & Electronics',
    'Compact Portable Speaker': 'Audio & Electronics',
    'Larger Portable Speaker': 'Audio & Electronics',
    'Ultra-portable Bluetooth Speaker': 'Audio & Electronics',
    'Mid-sized Bluetooth Speaker': 'Audio & Electronics',
    'Large Bluetooth Speaker': 'Audio & Electronics',
    'Large outdoor Bluetooth Speaker': 'Audio & Electronics',
    'Large party Bluetooth Speaker': 'Audio & Electronics',
    'Portable party Bluetooth Speaker': 'Audio & Electronics',
    'Hi-Res Bluetooth with spatial audio Speaker': 'Audio & Electronics',
    'Compact Bluetooth Speaker': 'Audio & Electronics',
    'Mini Bluetooth Speaker': 'Audio & Electronics',
    'Wireless Speaker': 'Audio & Electronics',
    'Ultra-compact portable Speaker': 'Audio & Electronics',
    'Compact portable Speaker': 'Audio & Electronics',
    'Mid-sized portable Speaker': 'Audio & Electronics',
    'Portable with handle Speaker': 'Audio & Electronics',
    'Large portable with handle Speaker': 'Audio & Electronics',
    'Compact home Speaker': 'Audio & Electronics',
    'Mid-sized home Speaker': 'Audio & Electronics',
    'Large home Speaker': 'Audio & Electronics',
    'Home Smart Speaker': 'Audio & Electronics',
    'Home Bluetooth Speaker': 'Audio & Electronics',
    'Compact & Ultra-Portable Speaker': 'Audio & Electronics',
    'Large & Party Speaker': 'Audio & Electronics',
    
    # Automotive
    'Pickup Truck': 'Automotive',
    'SUV': 'Automotive',
    'Sports Car': 'Automotive',
    'Compact SUV': 'Automotive',
    'Compact Truck': 'Automotive',
    'Electric Pickup Truck': 'Automotive',
    'Electric SUV': 'Automotive',
    'Electric Subcompact SUV': 'Automotive',
    'Electric Compact Crossover': 'Automotive',
    'Midsize Crossover': 'Automotive',
    'Hot Hatch': 'Automotive',
    'Full-Size SUV': 'Automotive',
    'Full-Size Pickup Truck': 'Automotive',
    'Midsize SUV': 'Automotive',
    'Midsize Sedan': 'Automotive',
    'Compact Sedan/Hatchback': 'Automotive',
    'Hybrid Hatchback': 'Automotive',
    'Sports Car (Hybrid)': 'Automotive',
    'Sports Coupe (Hybrid)': 'Automotive',
    'Midsize Pickup Truck': 'Automotive',
    'Minivan': 'Automotive',
    'Subcompact SUV': 'Automotive',
    'Electric Midsize SUV': 'Automotive',
    'Electric Compact SUV': 'Automotive',
    'Electric Full-Size Pickup': 'Automotive',
    'Electric Full-Size SUV': 'Automotive',
    'Electric Luxury Sedan': 'Automotive',
    'Electric Sedan': 'Automotive',
    'High-Performance Estate': 'Automotive',
    'High-Performance Coupe': 'Automotive',
    'Executive Sedan': 'Automotive',
    'Electric Executive Sedan': 'Automotive',
    'High-Performance Sedan': 'Automotive',
    'Luxury 4×4 SUV': 'Automotive',
    'Plug-in Hybrid Luxury SUV': 'Automotive',
    'Full-Size Luxury Sedan': 'Automotive',
    'Electric Full-Size Luxury SUV': 'Automotive',
    'Electric Full-Size Luxury Sedan': 'Automotive',
    'Electric Subcompact Luxury Crossover': 'Automotive',
    'Electric Compact Luxury Crossover': 'Automotive',
    'Subcompact Luxury Crossover': 'Automotive',
    'Full-Size Luxury Hybrid SUV': 'Automotive',
    'Subcompact Luxury Crossover SUV': 'Automotive',
    'Full-Size Luxury Crossover SUV': 'Automotive',
    'Electric Mid-Size Luxury Crossover SUV': 'Automotive',
    'Full-Size Luxury SUV': 'Automotive',
    'Compact Luxury Crossover SUV': 'Automotive',
    'Mid-Size Luxury Crossover SUV': 'Automotive',
    'Electric Mid-Size Luxury SUV': 'Automotive',
    'Compact Executive Car': 'Automotive',
    'Electric Compact Luxury Crossover SUV': 'Automotive',
    'Electric Luxury Sports Sedan': 'Automotive',
    'Coupe': 'Automotive',
    'Cabriolet': 'Automotive',
    'Targa': 'Automotive',
    'Sedan': 'Automotive',
    'Hypercar': 'Automotive',
    'Convertible': 'Automotive',
    'Grand Tourer': 'Automotive',
    'Coupé': 'Automotive',
    'Electric Coupé': 'Automotive',
    'Single-Motor': 'Automotive',
    'Dual-Motor': 'Automotive',
    'Tri-Motor': 'Automotive',
    'Tesla Y': 'Automotive',
    'Tesla X': 'Automotive',
    'Tesla 3': 'Automotive',
    'Tesla S': 'Automotive',
    
    # Food & Groceries - Meat & Poultry
    'Whole Chicken': 'Food & Groceries',
    'Wings': 'Food & Groceries',
    'Drumsticks': 'Food & Groceries',
    'Boneless Breast': 'Food & Groceries',
    'Thighs': 'Food & Groceries',
    'Legs': 'Food & Groceries',
    'Breast': 'Food & Groceries',
    'Strips': 'Food & Groceries',
    'Bone-in Breast': 'Food & Groceries',
    'Tenderloin Steak': 'Food & Groceries',
    'T-bone Steak': 'Food & Groceries',
    'New York Strip Steak': 'Food & Groceries',
    'Chuck Steak': 'Food & Groceries',
    'Round Steak': 'Food & Groceries',
    'Flunk Steak': 'Food & Groceries',
    'Sirloin': 'Food & Groceries',
    'Gound': 'Food & Groceries',
    'Diced': 'Food & Groceries',
    'Bone-in Loin': 'Food & Groceries',
    'Boneless Loin': 'Food & Groceries',
    'Shoulder Blade': 'Food & Groceries',
    'Shoulder Picnic': 'Food & Groceries',
    'Belly': 'Food & Groceries',
    'Chop': 'Food & Groceries',
    'Tenderloin': 'Food & Groceries',
    'Rib Racks': 'Food & Groceries',
    'Petite Racks': 'Food & Groceries',
    'Jowl': 'Food & Groceries',
    'Ground': 'Food & Groceries',
    'Iowl (Cheek)': 'Food & Groceries',
    
    # Food & Groceries - Seafood
    'Salmon Fillet Skin-on': 'Food & Groceries',
    'Salmon Fillet Skinless': 'Food & Groceries',
    'Salmon Portion-cut Fillet': 'Food & Groceries',
    'Salmon Steak Bone-in': 'Food & Groceries',
    'Salmon Steak Boneless': 'Food & Groceries',
    'Salmon Belly': 'Food & Groceries',
    'Smoked Salmon': 'Food & Groceries',
    'Tuna Akami': 'Food & Groceries',
    'Tuna Chutoro': 'Food & Groceries',
    'Tuna Otoro': 'Food & Groceries',
    'Tilapia Whole': 'Food & Groceries',
    'Cod': 'Food & Groceries',
    'Catfish': 'Food & Groceries',
    'Pollock': 'Food & Groceries',
    'Shrimp': 'Food & Groceries',
    'Halibut': 'Food & Groceries',
    'Tilapia': 'Food & Groceries',
    'Salmon Portion‑cut Fillet': 'Food & Groceries',
    'Mahi-Mahi': 'Food & Groceries',
    'ASG Salmon Fillet Skin-on': 'Food & Groceries',
    'ASG Salmon Fillet Skinless': 'Food & Groceries',
    'ASG Salmon Portion‑cut Fillet': 'Food & Groceries',
    'ASG Salmon Steak Bone-in': 'Food & Groceries',
    'ASG Salmon Steak Boneless': 'Food & Groceries',
    'ASG Salmon Belly': 'Food & Groceries',
    'ASG Smoked Salmon': 'Food & Groceries',
    'ASG Akami': 'Food & Groceries',
    'ASG Akami Tuna': 'Food & Groceries',
    'ASG Chutoro Tuna': 'Food & Groceries',
    'ASG Otoro Tuna': 'Food & Groceries',
    'ASG Cod': 'Food & Groceries',
    'ASG Tilapia': 'Food & Groceries',
    'ASG Catfish': 'Food & Groceries',
    'ASG Pollock': 'Food & Groceries',
    'ASG Mahi Mahi': 'Food & Groceries',
    'ASG Shrimp': 'Food & Groceries',
    'Blue Point': 'Food & Groceries',
    'Kumamoto': 'Food & Groceries',
    'Wellfleet': 'Food & Groceries',
    'Hama Hama': 'Food & Groceries',
    'Island Creek': 'Food & Groceries',
    'King': 'Food & Groceries',
    'Snow': 'Food & Groceries',
    'Dungeness': 'Food & Groceries',
    'Surimi (Crab Delights)': 'Food & Groceries',
    'King Crab': 'Food & Groceries',
    'Snow Crab': 'Food & Groceries',
    'Dungeness Crab': 'Food & Groceries',
    'Soft Shell Crab': 'Food & Groceries',
    'Jumbo Lump Crab Meat': 'Food & Groceries',
    'Claw Crab Meat': 'Food & Groceries',
    'Backfin/Special Meat': 'Food & Groceries',
    'Special Crab Meat': 'Food & Groceries',
    'Lump Crab Meat': 'Food & Groceries',
    'Backfin (Special)': 'Food & Groceries',
    'Live Lobster': 'Food & Groceries',
    'Lobster Tail': 'Food & Groceries',
    'Cooked Lobster': 'Food & Groceries',
    'Raw Lobster Tail': 'Food & Groceries',
    
    # Food & Groceries - Vegetables & Produce
    'Chopped Salad Kits': 'Food & Groceries',
    'Classic Salad Kits': 'Food & Groceries',
    'Chopped Salad Bowls': 'Food & Groceries',
    'Vegetable Blends Salad': 'Food & Groceries',
    'Meal Kits & Trays Salad': 'Food & Groceries',
    'Fresh‑Cut Veggies Salad': 'Food & Groceries',
    'Baby Carrots': 'Food & Groceries',
    'Organic Baby Carrots': 'Food & Groceries',
    'Shredded Carrots': 'Food & Groceries',
    'Snack Packs Carrots': 'Food & Groceries',
    'Lettuce': 'Food & Groceries',
    'Broccoli': 'Food & Groceries',
    'Cauliflower': 'Food & Groceries',
    'Romaine Hearts': 'Food & Groceries',
    'Leaf Blends': 'Food & Groceries',
    'Spinach': 'Food & Groceries',
    'Radishes': 'Food & Groceries',
    'Carrots': 'Food & Groceries',
    'Kale': 'Food & Groceries',
    'Leaf': 'Food & Groceries',
    'Beets': 'Food & Groceries',
    'Bell Peppers': 'Food & Groceries',
    'Mini Sweet Peppers': 'Food & Groceries',
    'Chilis Peppers': 'Food & Groceries',
    'Organic Euro Cucumber': 'Food & Groceries',
    'Zucchini': 'Food & Groceries',
    'Yellow Squash': 'Food & Groceries',
    'Snipped Green Beans': 'Food & Groceries',
    'Yellow Onions': 'Food & Groceries',
    'Red Onions': 'Food & Groceries',
    'Sweet Onions': 'Food & Groceries',
    'Green Onions': 'Food & Groceries',
    'Bagged Carrots (1 lb cello)': 'Food & Groceries',
    'Organic Carrots': 'Food & Groceries',
    'Sweet Corn': 'Food & Groceries',
    'Campari Tomatoes (10 oz)': 'Food & Groceries',
    'Cherry Tomatoes (10 oz)': 'Food & Groceries',
    'Beefsteak/Roma Tomatoes (each)': 'Food & Groceries',
    'Bell Peppers (cello pack)': 'Food & Groceries',
    'Mini/Specialty Peppers': 'Food & Groceries',
    'English Cucumbers (each)': 'Food & Groceries',
    'Mini Cucumbers (6‑pack)': 'Food & Groceries',
    'Tomatoes (cherry/Campari)': 'Food & Groceries',
    'Bell Peppers (clamshell)': 'Food & Groceries',
    'English Cucumbers': 'Food & Groceries',
    'Parsley': 'Food & Groceries',
    'Basil': 'Food & Groceries',
    'Cherry/Grape Tomatoes (1 lb)': 'Food & Groceries',
    'Vine-Ripened Tomatoes (bag)': 'Food & Groceries',
    'Sunny Crunch Lettuce (4 oz)': 'Food & Groceries',
    'Spring Mix (4 oz bag)': 'Food & Groceries',
    'Family Pack Lettuce (16 oz)': 'Food & Groceries',
    
    # Food & Groceries - Potatoes & Starches
    'White Russet™': 'Food & Groceries',
    'Innate® Russet Burbank': 'Food & Groceries',
    'Innate® Ranger Russet': 'Food & Groceries',
    'Innate® Atlantic': 'Food & Groceries',
    'Innate® Snowden': 'Food & Groceries',
    'Potato Pearls® Value (28 oz)': 'Food & Groceries',
    'Gold Extra Rich Mashed (59 oz)': 'Food & Groceries',
    'Low Sodium Mashed (57 oz)': 'Food & Groceries',
    'Instant Granules (5.31 lb pouch)': 'Food & Groceries',
    
    # Food & Groceries - Pasta
    'Spaghetti No. 5': 'Food & Groceries',
    'Thin Spaghetti': 'Food & Groceries',
    'Penne Rigate': 'Food & Groceries',
    'Rotini': 'Food & Groceries',
    'Farfalle': 'Food & Groceries',
    'Lasagne (Wavy)': 'Food & Groceries',
    'Ziti / Rigatoni': 'Food & Groceries',
    'Shells': 'Food & Groceries',
    'Orzo': 'Food & Groceries',
    'Mini Shells': 'Food & Groceries',
    'Ditalini': 'Food & Groceries',
    'Orzo Mini': 'Food & Groceries',
    'Cavatappi': 'Food & Groceries',
    'Bucatini': 'Food & Groceries',
    'Fusilli (Corkscrew)': 'Food & Groceries',
    'Angel Hair': 'Food & Groceries',
    'Lasagna Sheets (flat)': 'Food & Groceries',
    'Elbows (Small)': 'Food & Groceries',
    'Rotelle (Wagon Wheel)': 'Food & Groceries',
    
    # Food & Groceries - Coffee & Beverages
    'Whole Bean Coffee': 'Food & Groceries',
    'K-Cup Pods Coffee': 'Food & Groceries',
    'Ground Coffee': 'Food & Groceries',
    'Soluble Coffee': 'Food & Groceries',
    'Capsules Coffee': 'Food & Groceries',
    'Espresso': 'Food & Groceries',
    'Pod Coffee': 'Food & Groceries',
    'Decaf': 'Food & Groceries',
    'WHole Bean Coffee': 'Food & Groceries',
    'Special Blends Coffee': 'Food & Groceries',
    'Instant Coffee': 'Food & Groceries',
    'Cold Brew Coffee': 'Food & Groceries',
    'Flavored Coffee': 'Food & Groceries',
    'Seasonal Coffee': 'Food & Groceries',
    'Energy Drinks': 'Food & Groceries',
    'Low-Calorie Frappuccino': 'Food & Groceries',
    'Espresso Shots': 'Food & Groceries',
    'Bottled Frappuccino': 'Food & Groceries',
    'Canned Iced Espresso/Latte': 'Food & Groceries',
    'Bottled Iced Coffee / Lattes': 'Food & Groceries',
    'K-Cup Pod Coffee': 'Food & Groceries',
    'Instant Cold Brew': 'Food & Groceries',
    'Espresso Pod': 'Food & Groceries',
    'Instant Coffee Unit': 'Food & Groceries',
    'Dark Roast Ground': 'Food & Groceries',
    'Instant Dark Roast': 'Food & Groceries',
    'Instant Decaf': 'Food & Groceries',
    'Iced Beverage': 'Food & Groceries',
    'Ground Cofee': 'Food & Groceries',
    'Instant Decafe': 'Food & Groceries',
    'Instant Mix Beverage': 'Food & Groceries',
    'Instant Beverage Mix': 'Food & Groceries',
    'Decaf Pod': 'Food & Groceries',
    'Flavored Pod': 'Food & Groceries',
    'Instand Coffee': 'Food & Groceries',
    'Instant Stick Pack': 'Food & Groceries',
    'Espresso Pod Bulk': 'Food & Groceries',
    'Dolce Gusto Pod': 'Food & Groceries',
    'RTD Iced Coffee': 'Food & Groceries',
    'Instant Decaf Espresso': 'Food & Groceries',
    'Instant Mix': 'Food & Groceries',
    'Roast & Ground': 'Food & Groceries',
    'Instant Medium Roast': 'Food & Groceries',
    'Brewed Pod': 'Food & Groceries',
    'Light Roast Pod': 'Food & Groceries',
    'Dark Roast Pod': 'Food & Groceries',
    'Medium Roast Pod': 'Food & Groceries',
    'Ground Medium Roast': 'Food & Groceries',
    'Ground Espresso': 'Food & Groceries',
    'Ground Dark Roast': 'Food & Groceries',
    'Ground Medium-Dark': 'Food & Groceries',
    'Ground Decaf': 'Food & Groceries',
    'Ready-to-Drink': 'Food & Groceries',
    'Instant Espresso': 'Food & Groceries',
    'Medium Roast Ground': 'Food & Groceries',
    'Bulk Ground Medium Roast': 'Food & Groceries',
    'Medium-Light Roast Ground': 'Food & Groceries',
    'Medium-Dark Roast Ground': 'Food & Groceries',
    'Medium-Dark Pod': 'Food & Groceries',
    'Medium Roast Ground Decaf': 'Food & Groceries',
    'Flavored Pod Coffee': 'Food & Groceries',
    'Instant Coffee Decaf': 'Food & Groceries',
    'Espresso Ground': 'Food & Groceries',
    'Espresso Ground Decaf': 'Food & Groceries',
    'Instant Coffee Pod': 'Food & Groceries',
    'Seasonal Pod': 'Food & Groceries',
    'Dark Roast Bean': 'Food & Groceries',
    'Medium Roast Bean': 'Food & Groceries',
    'Light Roast Ground': 'Food & Groceries',
    'Decaf Ground': 'Food & Groceries',
    'Cold Brew': 'Food & Groceries',
    'Flavored Ground': 'Food & Groceries',
    'Cold Brew Ground': 'Food & Groceries',
    'Decaf Instant Coffee': 'Food & Groceries',
    'Premium Instant Coffee': 'Food & Groceries',
    'Premium Espresso Instant': 'Food & Groceries',
    'RTD Coffee': 'Food & Groceries',
    'Espresso Roast Ground': 'Food & Groceries',
    'Whole Bean': 'Food & Groceries',
    'Capsule': 'Food & Groceries',
    'Whole Been Coffee': 'Food & Groceries',
    'Instant': 'Food & Groceries',
    'RTD Cold Brew': 'Food & Groceries',
    'RTD': 'Food & Groceries',
    'Single-Serve Pods Coffee': 'Food & Groceries',
    'Single-Serve Pods': 'Food & Groceries',
    'Whole Bean Decaf': 'Food & Groceries',
    'Single-Serve Pod': 'Food & Groceries',
    'Flavored Ground Coffee': 'Food & Groceries'
}

